services:
  database:
    image: postgres
    container_name: bot_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgres_data/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5444:5432"
volumes:
  postgres_data:
